KUI 1140 change semester options
KTH/kurs-pm-data-admin-web pull request #371
Opened 2024-06-11 12:58 UTC by amirhossein-haerian

This PR is part of this task: https://kth-se.atlassian.net/browse/KUI-1140 
There is also another PR related to this task which is in the kurs-pm-admin-web repository with same branch name.
If you have any comments regarding the place of created files (or you think there is a better place for them) please share that as well.

2024-06-12 06:29 UTC, karlandindrakryggen requested changes
Looks good, but I would like you to look at and think about if `SemesterDropdown` needs an internal state.

2024-06-12 13:51 UTC, karlandindrakryggen approved these changes

2024-06-12 14:02 UTC, axelbjo approved these changes

2024-06-13 10:05 UTC, belanglos requested changes
Good stuff!
Similar comments as in the other repo, please hit me up if you have questions :)

2024-06-13 10:05 UTC, belanglos commented on public/js/app/components/SemesterDropdown.jsx
> +export default memo(SemesterDropdown)
Same comment as in the other repo. I think we do not need `memo` here.

2024-06-13 10:05 UTC, belanglos commented on public/js/app/pages/CreateNewMemo.jsx
> +  }, [])
Is eslint complaining about `_cleanUpPrevCheckboxesState` missing from the dep-array?

2024-06-13 10:05 UTC, belanglos commented on test/unit/helper.test.js
> +  it('should return error for an invalid date', () => {
🏅

2024-06-17 06:01 UTC, belanglos approved these changes
Great job!!

2024-06-17 11:23 UTC, merged