KUI-1448: Fetching data from Ladok mellanlager
KTH/kurs-pm-data-admin-web pull request #390
Opened 2024-09-24 14:16 UTC by axelbjo

- Ladok fields that have been implemented: [Confluence page](https://confluence.sys.kth.se/confluence/display/TJAN/Mappning+-+kurs-pm-data-admin-web)

2024-09-25 06:59 UTC, amirhossein-haerian approved these changes
The changes look great,
I have tested them with my latest changes and it is working for me 
Good job ⭐️

2024-09-25 08:02 UTC, karlandindrakryggen commented on test/unit/MemoContainerNewDraft.test.js
> +    expect(headers[0]).toHaveTextContent('Skapa och publicera kurs-PMEF1111 Projekt i plasmafysik 9.0 hp')
.

2024-09-25 08:28 UTC, karlandindrakryggen reviewed
Looks great! But I think we need to look into language handling when userlang != memolang. Maybe we can look at it together later today.

2024-09-25 08:28 UTC, karlandindrakryggen commented on server/ladokApi.js
> +        en: round.undervisningssprak.name === 'Svenska' ? 'Swedish' : 'English',
I wondering we can find a more elegant way to this with the data from Ladok. Maybe add a `nameOther` so that we always have the translation already.

2024-09-25 08:28 UTC, karlandindrakryggen commented on public/js/app/pages/MemoEditingContainer.jsx
> +    const courseTitle = `${courseCode} ${title} ${creditsStandard} ${userLangIndex === 1 ? creditUnitAbbr : 'credits'}`
I'm now sure about the lang of the title here. I think we might need to add something corresponding to `titleOther` in the data from Ladok.

2024-09-26 06:02 UTC, karlandindrakryggen requested changes

2024-09-26 06:02 UTC, karlandindrakryggen commented on server/ladokApi.js
> +      lastTuitionDate: round.sistaUndervisningsdatum,
Shouldn't it be `.date` for lastTuitionDate in same way as for firstTuitionDate?
```suggestion
      firstTuitionDate: round.forstaUndervisningsdatum.date,
      lastTuitionDate: round.sistaUndervisningsdatum.date,
```

2024-09-26 07:56 UTC, karlandindrakryggen approved these changes

2024-09-26 08:08 UTC, merged