KUI-1523: fix 'undefined' course title in sub header
KTH/kurs-pm-data-admin-web pull request #394
Opened 2024-10-30 12:56 UTC by axelbjo

- Handled correct mapping of credits and title for course title
- Updated tests

2024-10-30 15:49 UTC, karlandindrakryggen commented on public/js/app/util/helpers.js
> +  const courseName = `${courseCode} ${title} ${credits.number} ${creditUnit}`
We added this `formattedWithUnit` on course which should contains credits and unit formatted correctly for given language. So I think it's better to use that one.
```
const courseName = `${courseCode} ${title} ${credits.formattedWithUnit}`
```

2024-10-30 15:49 UTC, karlandindrakryggen commented on public/js/app/pages/MemoEditingContainer.jsx
> +    const creditsStandard = credits.number || ''
I guess my comment on `public/js/app/util/helpers.js` applies here as well.

2024-10-30 15:49 UTC, karlandindrakryggen commented on public/js/app/util/__test__/helpers.test.js
> +    expect(courseTitle).toBe('ML1616 Industriell projektledning och projektstyrning 7.5 hp')
This should be `7,5 hp` with , in swedish, but I think it will be fixed with `formattedWithUnit` prop

2024-10-31 08:22 UTC, amirhossein-haerian approved these changes
LGTM, I agree with Karl comments as well

2024-11-01 12:36 UTC, karlandindrakryggen commented
I've tested this and noticed that we made mistakes regarding languages earlier in the `upl-main` branch. So I think we need to take a steg back and fix that first.

We need to use **memo** language and **user** language in the correct places. First I noticed that the language of the title of the memo always will be created based on **user** language and not **memo** as in ref (might be introduced in this PR or earlier). And then I noticed that some content has incorrect language as well (not introduced in this PR). 

Feels like the code is very confusing about this from before, so my suggestion is that we look at this with together next week and try fix it and refactor it to make it more clear.

2024-11-18 15:48 UTC, axelbjo commented
Made it so that memo language is always used for fetching data. That seems to give the correct behaviour when I test it.

2024-11-29 13:21 UTC, karlandindrakryggen requested changes
I found a bug where a memo get wrong language, see my new comment in ladokApi.js.

I've looked into the tests in details, but as I wrote in the other PR they needs to be fixed (or removed if not useful anymore)

2024-12-03 14:59 UTC, karlandindrakryggen approved these changes

2024-12-05 09:44 UTC, merged