Issue/k UI 1601 remove fields
KTH/kurs-pm-data-admin-web pull request #396
Opened 2024-11-21 14:56 UTC by amirhossein-haerian

The auto-retrieval of the following fields from Kopps has been removed now. The fields/headings still remained in the course pm, but are empty from the start when you create a new pm.

Möjlighet till komplettering (possibilityToCompletion)

Möjlighet till plussning (possibilityToAddition)

Utrustning (requiredEquipment)

2024-11-27 06:55 UTC, allazis requested changes
Great job! I added some comments with suggestions on how to adjust the test file. Since the literature is no longer fetched from kopps, it should be excluded form the kopps template. As a result the added parsing of the kopps api mock result wont be needed.

2024-11-27 06:55 UTC, allazis commented on test/unit/memoCtrl.test.js
>    literatureTemplate: '<p>Text fetched from kopps and can be edited, removed</p>',
```suggestion
```

2024-11-27 06:55 UTC, allazis commented on test/unit/memoCtrl.test.js
> +    const { examinationSubSection, literature } = updatedMemoData
```suggestion
const { examinationSubSection } = updatedMemoData
```

2024-11-27 06:55 UTC, allazis commented on test/unit/memoCtrl.test.js
>      expect(literature).toBe(mockedKoppsTemplates.literatureTemplate)
```suggestion
```

2024-11-27 06:55 UTC, allazis commented on test/unit/memoCtrl.test.js
> +      JSON.parse(JSON.stringify(mockedKoppsTemplates)),
If the above suggestions are applied, this parsing wont be needed.

```suggestion
mockedKoppsTemplates,
```

2024-11-27 06:55 UTC, allazis commented on test/unit/memoCtrl.test.js
> +      JSON.parse(JSON.stringify(mockedKoppsTemplates)),
If the above suggestions are applied, this parsing wont be needed.

```suggestion
mockedKoppsTemplates,
```

2024-11-27 06:55 UTC, allazis commented on test/unit/memoCtrl.test.js
> +  "literature": "<p>Text fetched from kopps and can be edited, removed</p>",
This wont be relevant either

```suggestion
"literature": "",
```

2024-11-27 07:04 UTC, allazis commented
Mistakenly reviewed changes from https://github.com/KTH/kurs-pm-data-admin-web/pull/405 within this PR. Please ignore above comments, as I will review them separately.

2024-11-27 07:57 UTC, allazis approved these changes

2024-11-27 07:59 UTC, allazis commented
We maybe need to look`memoCtrl` testfile through but we can save it for [PR-405](https://github.com/KTH/kurs-pm-data-admin-web/pull/405 )

Well done!

2024-12-02 10:08 UTC, axelbjo approved these changes
Looks good to me!

2024-12-02 12:18 UTC, karlandindrakryggen approved these changes

2024-12-02 12:49 UTC, karlandindrakryggen commented
Wait with merging this until we have decided about what to include in release later this week.

2025-01-24 07:14 UTC, merged